### ISSUE TITLE
Problem when load XML metadata

### ISSUE THREAD

**Issue by marciotheis** [flat3/lodata#287]
Hi @27pchrisl 

When I tried to load the XML metadata http://localhost:8000/odata/$metadata its generated an error because some fields in my database has the default value int.

```
TypeError: SimpleXMLElement::addAttribute(): Argument #2 ($value) must be of type string, int given in file C:\Projects\odata\vendor\flat3\lodata\src\PathSegment\Metadata\XML.php on line 161

#0 C:\Projects\odata\vendor\flat3\lodata\src\PathSegment\Metadata\XML.php(161): SimpleXMLElement->addAttribute()
#1 C:\Projects\odata\vendor\flat3\lodata\src\PathSegment\Metadata\XML.php(350): Flat3\Lodata\PathSegment\Metadata\XML->emitStream()
#2 C:\Projects\odata\vendor\symfony\http-foundation\StreamedResponse.php(93): Flat3\Lodata\PathSegment\Metadata\XML->Flat3\Lodata\PathSegment\Metadata\{closure}()
#3 C:\Projects\odata\vendor\flat3\lodata\src\Controller\Response.php(96): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#4 C:\Projects\odata\vendor\flat3\lodata\src\Controller\Response.php(144): Flat3\Lodata\Controller\Response->sendContentStreamed()
#5 C:\Projects\odata\vendor\flat3\lodata\src\Helper\Symfony\Response6.php(17): Flat3\Lodata\Controller\Response->_sendContent()
#6 C:\Projects\odata\vendor\symfony\http-foundation\Response.php(373): Flat3\Lodata\Helper\Symfony\Response6->sendContent()
#7 C:\Projects\odata\public\index.php(53): Symfony\Component\HttpFoundation\Response->send()
#8 {main}
```

But when editing the file src/PathSegment/Metadata/XML.php function emitStream line 161 and adding (string) $property->computeDefaultValue()->toJson() works very vell.

```
                if ($property->hasStaticDefaultValue()) {
                    $entityTypeProperty->addAttribute('DefaultValue', (string) $property->computeDefaultValue()->toJson());
                }
```

Thanks !

**Comment by 27pchrisl** [comment]
Thanks for the report! Fixed in 5.x-dev. I will release once you verify it fixes your other issue

**Comment by 27pchrisl** [comment]
Resolved in https://github.com/flat3/lodata/releases/tag/v5.18.0
